// @generated by protobuf-ts 2.9.3 with parameter output_javascript_es2018
// @generated from protobuf file "proto/todolist.proto" (package "core", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Todo } from "./todo";
/**
 * @generated from protobuf message core.GetTodosOut
 */
export interface GetTodosOut {
    /**
     * @generated from protobuf field: repeated core.Todo todos = 1;
     */
    todos: Todo[];
}
/**
 * @generated from protobuf message core.NewTodoIn
 */
export interface NewTodoIn {
    /**
     * @generated from protobuf field: string content = 1;
     */
    content: string;
}
/**
 * @generated from protobuf message core.NewTodoOut
 */
export interface NewTodoOut {
    /**
     * @generated from protobuf field: core.Todo todo = 1;
     */
    todo?: Todo;
}
/**
 * @generated from protobuf message core.EditTodoOut
 */
export interface EditTodoOut {
    /**
     * @generated from protobuf field: core.Todo todo = 1;
     */
    todo?: Todo;
}
/**
 * @generated from protobuf message core.CheckTodoIn
 */
export interface CheckTodoIn {
    /**
     * @generated from protobuf field: string id = 1;
     */
    id: string;
    /**
     * @generated from protobuf field: bool completed = 2;
     */
    completed: boolean;
}
/**
 * @generated from protobuf message core.CheckTodoOut
 */
export interface CheckTodoOut {
    /**
     * @generated from protobuf field: core.Todo todo = 1;
     */
    todo?: Todo;
}
/**
 * @generated from protobuf message core.DeleteTodoIn
 */
export interface DeleteTodoIn {
    /**
     * @generated from protobuf field: string id = 1;
     */
    id: string;
}
declare class GetTodosOut$Type extends MessageType<GetTodosOut> {
    constructor();
    create(value?: PartialMessage<GetTodosOut>): GetTodosOut;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetTodosOut): GetTodosOut;
    internalBinaryWrite(message: GetTodosOut, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message core.GetTodosOut
 */
export declare const GetTodosOut: GetTodosOut$Type;
declare class NewTodoIn$Type extends MessageType<NewTodoIn> {
    constructor();
    create(value?: PartialMessage<NewTodoIn>): NewTodoIn;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: NewTodoIn): NewTodoIn;
    internalBinaryWrite(message: NewTodoIn, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message core.NewTodoIn
 */
export declare const NewTodoIn: NewTodoIn$Type;
declare class NewTodoOut$Type extends MessageType<NewTodoOut> {
    constructor();
    create(value?: PartialMessage<NewTodoOut>): NewTodoOut;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: NewTodoOut): NewTodoOut;
    internalBinaryWrite(message: NewTodoOut, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message core.NewTodoOut
 */
export declare const NewTodoOut: NewTodoOut$Type;
declare class EditTodoOut$Type extends MessageType<EditTodoOut> {
    constructor();
    create(value?: PartialMessage<EditTodoOut>): EditTodoOut;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EditTodoOut): EditTodoOut;
    internalBinaryWrite(message: EditTodoOut, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message core.EditTodoOut
 */
export declare const EditTodoOut: EditTodoOut$Type;
declare class CheckTodoIn$Type extends MessageType<CheckTodoIn> {
    constructor();
    create(value?: PartialMessage<CheckTodoIn>): CheckTodoIn;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CheckTodoIn): CheckTodoIn;
    internalBinaryWrite(message: CheckTodoIn, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message core.CheckTodoIn
 */
export declare const CheckTodoIn: CheckTodoIn$Type;
declare class CheckTodoOut$Type extends MessageType<CheckTodoOut> {
    constructor();
    create(value?: PartialMessage<CheckTodoOut>): CheckTodoOut;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CheckTodoOut): CheckTodoOut;
    internalBinaryWrite(message: CheckTodoOut, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message core.CheckTodoOut
 */
export declare const CheckTodoOut: CheckTodoOut$Type;
declare class DeleteTodoIn$Type extends MessageType<DeleteTodoIn> {
    constructor();
    create(value?: PartialMessage<DeleteTodoIn>): DeleteTodoIn;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteTodoIn): DeleteTodoIn;
    internalBinaryWrite(message: DeleteTodoIn, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message core.DeleteTodoIn
 */
export declare const DeleteTodoIn: DeleteTodoIn$Type;
/**
 * @generated ServiceType for protobuf service core.TodoListService
 */
export declare const TodoListService: any;
export {};
