// @generated by protobuf-ts 2.9.3 with parameter output_javascript_es2018
// @generated from protobuf file "proto/todo.proto" (package "core", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message core.Todo
 */
export interface Todo {
    /**
     * @generated from protobuf field: string id = 1;
     */
    id: string;
    /**
     * @generated from protobuf field: string content = 2;
     */
    content: string;
    /**
     * @generated from protobuf field: bool completed = 3;
     */
    completed: boolean;
}
declare class Todo$Type extends MessageType<Todo> {
    constructor();
    create(value?: PartialMessage<Todo>): Todo;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Todo): Todo;
    internalBinaryWrite(message: Todo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message core.Todo
 */
export declare const Todo: Todo$Type;
export {};
