// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: proto/liveclass.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LiveclassServiceClient is the client API for LiveclassService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LiveclassServiceClient interface {
	List(ctx context.Context, in *LiveclassIn, opts ...grpc.CallOption) (*LiveclassOut, error)
}

type liveclassServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLiveclassServiceClient(cc grpc.ClientConnInterface) LiveclassServiceClient {
	return &liveclassServiceClient{cc}
}

func (c *liveclassServiceClient) List(ctx context.Context, in *LiveclassIn, opts ...grpc.CallOption) (*LiveclassOut, error) {
	out := new(LiveclassOut)
	err := c.cc.Invoke(ctx, "/core.LiveclassService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LiveclassServiceServer is the server API for LiveclassService service.
// All implementations must embed UnimplementedLiveclassServiceServer
// for forward compatibility
type LiveclassServiceServer interface {
	List(context.Context, *LiveclassIn) (*LiveclassOut, error)
	mustEmbedUnimplementedLiveclassServiceServer()
}

// UnimplementedLiveclassServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLiveclassServiceServer struct {
}

func (UnimplementedLiveclassServiceServer) List(context.Context, *LiveclassIn) (*LiveclassOut, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedLiveclassServiceServer) mustEmbedUnimplementedLiveclassServiceServer() {}

// UnsafeLiveclassServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LiveclassServiceServer will
// result in compilation errors.
type UnsafeLiveclassServiceServer interface {
	mustEmbedUnimplementedLiveclassServiceServer()
}

func RegisterLiveclassServiceServer(s grpc.ServiceRegistrar, srv LiveclassServiceServer) {
	s.RegisterService(&LiveclassService_ServiceDesc, srv)
}

func _LiveclassService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LiveclassIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiveclassServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/core.LiveclassService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiveclassServiceServer).List(ctx, req.(*LiveclassIn))
	}
	return interceptor(ctx, in, info, handler)
}

// LiveclassService_ServiceDesc is the grpc.ServiceDesc for LiveclassService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LiveclassService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "core.LiveclassService",
	HandlerType: (*LiveclassServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _LiveclassService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/liveclass.proto",
}
