// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: proto/teacher.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnrollWithTeacherResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TeacherID    string `protobuf:"bytes,1,opt,name=teacherID,proto3" json:"teacherID,omitempty"`
	EnrollmentID string `protobuf:"bytes,2,opt,name=enrollmentID,proto3" json:"enrollmentID,omitempty"`
	AccountID    string `protobuf:"bytes,3,opt,name=accountID,proto3" json:"accountID,omitempty"`
	Attach       string `protobuf:"bytes,4,opt,name=attach,proto3" json:"attach,omitempty"`
	Attach2      string `protobuf:"bytes,5,opt,name=attach2,proto3" json:"attach2,omitempty"`
	Attach3      string `protobuf:"bytes,6,opt,name=attach3,proto3" json:"attach3,omitempty"`
	DemoClass    string `protobuf:"bytes,7,opt,name=demoClass,proto3" json:"demoClass,omitempty"`
	Email        string `protobuf:"bytes,8,opt,name=email,proto3" json:"email,omitempty"`
	Name         string `protobuf:"bytes,9,opt,name=name,proto3" json:"name,omitempty"`
	Country      string `protobuf:"bytes,10,opt,name=country,proto3" json:"country,omitempty"`
	Zipcode      string `protobuf:"bytes,11,opt,name=zipcode,proto3" json:"zipcode,omitempty"`
	Gender       string `protobuf:"bytes,12,opt,name=gender,proto3" json:"gender,omitempty"`
	Status       string `protobuf:"bytes,13,opt,name=status,proto3" json:"status,omitempty"`
	Step         string `protobuf:"bytes,14,opt,name=step,proto3" json:"step,omitempty"`
}

func (x *EnrollWithTeacherResult) Reset() {
	*x = EnrollWithTeacherResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_teacher_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnrollWithTeacherResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollWithTeacherResult) ProtoMessage() {}

func (x *EnrollWithTeacherResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollWithTeacherResult.ProtoReflect.Descriptor instead.
func (*EnrollWithTeacherResult) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollWithTeacherResult) GetTeacherID() string {
	if x != nil {
		return x.TeacherID
	}
	return ""
}

func (x *EnrollWithTeacherResult) GetEnrollmentID() string {
	if x != nil {
		return x.EnrollmentID
	}
	return ""
}

func (x *EnrollWithTeacherResult) GetAccountID() string {
	if x != nil {
		return x.AccountID
	}
	return ""
}

func (x *EnrollWithTeacherResult) GetAttach() string {
	if x != nil {
		return x.Attach
	}
	return ""
}

func (x *EnrollWithTeacherResult) GetAttach2() string {
	if x != nil {
		return x.Attach2
	}
	return ""
}

func (x *EnrollWithTeacherResult) GetAttach3() string {
	if x != nil {
		return x.Attach3
	}
	return ""
}

func (x *EnrollWithTeacherResult) GetDemoClass() string {
	if x != nil {
		return x.DemoClass
	}
	return ""
}

func (x *EnrollWithTeacherResult) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *EnrollWithTeacherResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnrollWithTeacherResult) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *EnrollWithTeacherResult) GetZipcode() string {
	if x != nil {
		return x.Zipcode
	}
	return ""
}

func (x *EnrollWithTeacherResult) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *EnrollWithTeacherResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EnrollWithTeacherResult) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

type RegisterTeacherIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fullname string `protobuf:"bytes,1,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	// optional field
	CallbackURL *string `protobuf:"bytes,4,opt,name=callbackURL,proto3,oneof" json:"callbackURL,omitempty"`
}

func (x *RegisterTeacherIn) Reset() {
	*x = RegisterTeacherIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_teacher_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterTeacherIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTeacherIn) ProtoMessage() {}

func (x *RegisterTeacherIn) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTeacherIn.ProtoReflect.Descriptor instead.
func (*RegisterTeacherIn) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterTeacherIn) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

func (x *RegisterTeacherIn) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterTeacherIn) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterTeacherIn) GetCallbackURL() string {
	if x != nil && x.CallbackURL != nil {
		return *x.CallbackURL
	}
	return ""
}

type RegisterTeacherOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Fullname string `protobuf:"bytes,2,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Email    string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Role     string `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
}

func (x *RegisterTeacherOut) Reset() {
	*x = RegisterTeacherOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_teacher_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterTeacherOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTeacherOut) ProtoMessage() {}

func (x *RegisterTeacherOut) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTeacherOut.ProtoReflect.Descriptor instead.
func (*RegisterTeacherOut) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterTeacherOut) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterTeacherOut) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

func (x *RegisterTeacherOut) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterTeacherOut) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterTeacherOut) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type SearchTeacherIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SearchTeacherIn) Reset() {
	*x = SearchTeacherIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_teacher_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchTeacherIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTeacherIn) ProtoMessage() {}

func (x *SearchTeacherIn) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTeacherIn.ProtoReflect.Descriptor instead.
func (*SearchTeacherIn) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{3}
}

type SearchTeacherOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SearchTeacherOut) Reset() {
	*x = SearchTeacherOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_teacher_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchTeacherOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTeacherOut) ProtoMessage() {}

func (x *SearchTeacherOut) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTeacherOut.ProtoReflect.Descriptor instead.
func (*SearchTeacherOut) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{4}
}

type EditEnrollmentStepIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EditEnrollmentStepIn) Reset() {
	*x = EditEnrollmentStepIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_teacher_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditEnrollmentStepIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditEnrollmentStepIn) ProtoMessage() {}

func (x *EditEnrollmentStepIn) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditEnrollmentStepIn.ProtoReflect.Descriptor instead.
func (*EditEnrollmentStepIn) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{5}
}

type EditEnrollmentStepOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EditEnrollmentStepOut) Reset() {
	*x = EditEnrollmentStepOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_teacher_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditEnrollmentStepOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditEnrollmentStepOut) ProtoMessage() {}

func (x *EditEnrollmentStepOut) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditEnrollmentStepOut.ProtoReflect.Descriptor instead.
func (*EditEnrollmentStepOut) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{6}
}

type ConfirmEnrollmentIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Accept    bool   `protobuf:"varint,1,opt,name=accept,proto3" json:"accept,omitempty"`
	TeacherID string `protobuf:"bytes,2,opt,name=teacherID,proto3" json:"teacherID,omitempty"`
}

func (x *ConfirmEnrollmentIn) Reset() {
	*x = ConfirmEnrollmentIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_teacher_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfirmEnrollmentIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmEnrollmentIn) ProtoMessage() {}

func (x *ConfirmEnrollmentIn) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmEnrollmentIn.ProtoReflect.Descriptor instead.
func (*ConfirmEnrollmentIn) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{7}
}

func (x *ConfirmEnrollmentIn) GetAccept() bool {
	if x != nil {
		return x.Accept
	}
	return false
}

func (x *ConfirmEnrollmentIn) GetTeacherID() string {
	if x != nil {
		return x.TeacherID
	}
	return ""
}

type ConfirmEnrollmentOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ConfirmEnrollmentOut) Reset() {
	*x = ConfirmEnrollmentOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_teacher_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfirmEnrollmentOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmEnrollmentOut) ProtoMessage() {}

func (x *ConfirmEnrollmentOut) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmEnrollmentOut.ProtoReflect.Descriptor instead.
func (*ConfirmEnrollmentOut) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{8}
}

type ConfirmLiveClasIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Confirm bool `protobuf:"varint,1,opt,name=confirm,proto3" json:"confirm,omitempty"`
}

func (x *ConfirmLiveClasIn) Reset() {
	*x = ConfirmLiveClasIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_teacher_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfirmLiveClasIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmLiveClasIn) ProtoMessage() {}

func (x *ConfirmLiveClasIn) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmLiveClasIn.ProtoReflect.Descriptor instead.
func (*ConfirmLiveClasIn) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{9}
}

func (x *ConfirmLiveClasIn) GetConfirm() bool {
	if x != nil {
		return x.Confirm
	}
	return false
}

type ConfirmLiveClassOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ConfirmLiveClassOut) Reset() {
	*x = ConfirmLiveClassOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_teacher_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfirmLiveClassOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmLiveClassOut) ProtoMessage() {}

func (x *ConfirmLiveClassOut) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmLiveClassOut.ProtoReflect.Descriptor instead.
func (*ConfirmLiveClassOut) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{10}
}

type GetEnrollmentsOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enrollments []*Enrollment `protobuf:"bytes,1,rep,name=enrollments,proto3" json:"enrollments,omitempty"`
}

func (x *GetEnrollmentsOut) Reset() {
	*x = GetEnrollmentsOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_teacher_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEnrollmentsOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnrollmentsOut) ProtoMessage() {}

func (x *GetEnrollmentsOut) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnrollmentsOut.ProtoReflect.Descriptor instead.
func (*GetEnrollmentsOut) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{11}
}

func (x *GetEnrollmentsOut) GetEnrollments() []*Enrollment {
	if x != nil {
		return x.Enrollments
	}
	return nil
}

type EnrollBasicInfoIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Country string `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	Zipcode string `protobuf:"bytes,2,opt,name=zipcode,proto3" json:"zipcode,omitempty"`
	Gender  string `protobuf:"bytes,3,opt,name=gender,proto3" json:"gender,omitempty"`
}

func (x *EnrollBasicInfoIn) Reset() {
	*x = EnrollBasicInfoIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_teacher_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnrollBasicInfoIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollBasicInfoIn) ProtoMessage() {}

func (x *EnrollBasicInfoIn) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollBasicInfoIn.ProtoReflect.Descriptor instead.
func (*EnrollBasicInfoIn) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{12}
}

func (x *EnrollBasicInfoIn) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *EnrollBasicInfoIn) GetZipcode() string {
	if x != nil {
		return x.Zipcode
	}
	return ""
}

func (x *EnrollBasicInfoIn) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

type Certificate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ext      string `protobuf:"bytes,1,opt,name=ext,proto3" json:"ext,omitempty"`
	FileName string `protobuf:"bytes,2,opt,name=fileName,proto3" json:"fileName,omitempty"`
	Binary   []byte `protobuf:"bytes,3,opt,name=binary,proto3" json:"binary,omitempty"`
}

func (x *Certificate) Reset() {
	*x = Certificate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_teacher_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Certificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Certificate) ProtoMessage() {}

func (x *Certificate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Certificate.ProtoReflect.Descriptor instead.
func (*Certificate) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{13}
}

func (x *Certificate) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

func (x *Certificate) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *Certificate) GetBinary() []byte {
	if x != nil {
		return x.Binary
	}
	return nil
}

type EnrollCertificatesIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Certificates []*Certificate `protobuf:"bytes,1,rep,name=certificates,proto3" json:"certificates,omitempty"`
}

func (x *EnrollCertificatesIn) Reset() {
	*x = EnrollCertificatesIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_teacher_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnrollCertificatesIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollCertificatesIn) ProtoMessage() {}

func (x *EnrollCertificatesIn) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollCertificatesIn.ProtoReflect.Descriptor instead.
func (*EnrollCertificatesIn) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{14}
}

func (x *EnrollCertificatesIn) GetCertificates() []*Certificate {
	if x != nil {
		return x.Certificates
	}
	return nil
}

type EnrollDemoClassIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoLink string `protobuf:"bytes,1,opt,name=videoLink,proto3" json:"videoLink,omitempty"`
}

func (x *EnrollDemoClassIn) Reset() {
	*x = EnrollDemoClassIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_teacher_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnrollDemoClassIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollDemoClassIn) ProtoMessage() {}

func (x *EnrollDemoClassIn) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollDemoClassIn.ProtoReflect.Descriptor instead.
func (*EnrollDemoClassIn) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{15}
}

func (x *EnrollDemoClassIn) GetVideoLink() string {
	if x != nil {
		return x.VideoLink
	}
	return ""
}

type EnrollAcceptContractIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Accept bool `protobuf:"varint,1,opt,name=accept,proto3" json:"accept,omitempty"`
}

func (x *EnrollAcceptContractIn) Reset() {
	*x = EnrollAcceptContractIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_teacher_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnrollAcceptContractIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollAcceptContractIn) ProtoMessage() {}

func (x *EnrollAcceptContractIn) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollAcceptContractIn.ProtoReflect.Descriptor instead.
func (*EnrollAcceptContractIn) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{16}
}

func (x *EnrollAcceptContractIn) GetAccept() bool {
	if x != nil {
		return x.Accept
	}
	return false
}

type GetPendingEnrollmentsOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enrollments []*EnrollWithTeacherResult `protobuf:"bytes,1,rep,name=enrollments,proto3" json:"enrollments,omitempty"`
}

func (x *GetPendingEnrollmentsOut) Reset() {
	*x = GetPendingEnrollmentsOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_teacher_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPendingEnrollmentsOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingEnrollmentsOut) ProtoMessage() {}

func (x *GetPendingEnrollmentsOut) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingEnrollmentsOut.ProtoReflect.Descriptor instead.
func (*GetPendingEnrollmentsOut) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{17}
}

func (x *GetPendingEnrollmentsOut) GetEnrollments() []*EnrollWithTeacherResult {
	if x != nil {
		return x.Enrollments
	}
	return nil
}

var File_proto_teacher_proto protoreflect.FileDescriptor

var file_proto_teacher_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63, 0x6f, 0x72, 0x65, 0x1a, 0x13, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x85, 0x03, 0x0a, 0x17, 0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x57, 0x69, 0x74, 0x68, 0x54,
	0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x6e,
	0x72, 0x6f, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x65, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x1c,
	0x0a, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x74,
	0x74, 0x61, 0x63, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x32, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x32, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x33, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x33, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x65, 0x6d, 0x6f,
	0x43, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x65, 0x6d,
	0x6f, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x7a, 0x69,
	0x70, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x7a, 0x69, 0x70,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x74, 0x65, 0x70, 0x18, 0x0e, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x73, 0x74, 0x65, 0x70, 0x22, 0x98, 0x01, 0x0a, 0x11, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x49, 0x6e, 0x12, 0x1a,
	0x0a, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x25, 0x0a, 0x0b,
	0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x55, 0x52, 0x4c, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x0b, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x55, 0x52, 0x4c,
	0x88, 0x01, 0x01, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b,
	0x55, 0x52, 0x4c, 0x22, 0x86, 0x01, 0x0a, 0x12, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x4f, 0x75, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x75,
	0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x75,
	0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x22, 0x11, 0x0a, 0x0f,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x49, 0x6e, 0x22,
	0x12, 0x0a, 0x10, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72,
	0x4f, 0x75, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x45, 0x64, 0x69, 0x74, 0x45, 0x6e, 0x72, 0x6f, 0x6c,
	0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x65, 0x70, 0x49, 0x6e, 0x22, 0x17, 0x0a, 0x15, 0x45,
	0x64, 0x69, 0x74, 0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x65,
	0x70, 0x4f, 0x75, 0x74, 0x22, 0x4b, 0x0a, 0x13, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x45,
	0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x63, 0x63, 0x65, 0x70, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x61, 0x63, 0x63,
	0x65, 0x70, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x49,
	0x44, 0x22, 0x16, 0x0a, 0x14, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x45, 0x6e, 0x72, 0x6f,
	0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x4f, 0x75, 0x74, 0x22, 0x2d, 0x0a, 0x11, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x72, 0x6d, 0x4c, 0x69, 0x76, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x49, 0x6e, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x22, 0x15, 0x0a, 0x13, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x72, 0x6d, 0x4c, 0x69, 0x76, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x4f, 0x75, 0x74, 0x22,
	0x47, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x4f, 0x75, 0x74, 0x12, 0x32, 0x0a, 0x0b, 0x65, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6f, 0x72, 0x65,
	0x2e, 0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0b, 0x65, 0x6e, 0x72,
	0x6f, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x5f, 0x0a, 0x11, 0x45, 0x6e, 0x72, 0x6f,
	0x6c, 0x6c, 0x42, 0x61, 0x73, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x49, 0x6e, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x7a, 0x69, 0x70, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x7a, 0x69, 0x70, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x22, 0x53, 0x0a, 0x0b, 0x43, 0x65, 0x72,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x78, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x22, 0x4d,
	0x0a, 0x14, 0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x65, 0x73, 0x49, 0x6e, 0x12, 0x35, 0x0a, 0x0c, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63,
	0x6f, 0x72, 0x65, 0x2e, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x52,
	0x0c, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x73, 0x22, 0x31, 0x0a,
	0x11, 0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x44, 0x65, 0x6d, 0x6f, 0x43, 0x6c, 0x61, 0x73, 0x73,
	0x49, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x4c, 0x69, 0x6e, 0x6b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x4c, 0x69, 0x6e, 0x6b,
	0x22, 0x30, 0x0a, 0x16, 0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74,
	0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x49, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63,
	0x63, 0x65, 0x70, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x61, 0x63, 0x63, 0x65,
	0x70, 0x74, 0x22, 0x5b, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x4f, 0x75, 0x74, 0x12, 0x3f,
	0x0a, 0x0b, 0x65, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x45, 0x6e, 0x72, 0x6f, 0x6c,
	0x6c, 0x57, 0x69, 0x74, 0x68, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x52, 0x0b, 0x65, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x32,
	0xb0, 0x06, 0x0a, 0x0e, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x44, 0x0a, 0x0f, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x65,
	0x61, 0x63, 0x68, 0x65, 0x72, 0x12, 0x17, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x49, 0x6e, 0x1a, 0x18,
	0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x65,
	0x61, 0x63, 0x68, 0x65, 0x72, 0x4f, 0x75, 0x74, 0x12, 0x3f, 0x0a, 0x0e, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x73, 0x12, 0x15, 0x2e, 0x63, 0x6f, 0x72,
	0x65, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x49,
	0x6e, 0x1a, 0x16, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54,
	0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x4f, 0x75, 0x74, 0x12, 0x4d, 0x0a, 0x12, 0x45, 0x64, 0x69,
	0x74, 0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x65, 0x70, 0x12,
	0x1a, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x45, 0x6e, 0x72, 0x6f, 0x6c,
	0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x65, 0x70, 0x49, 0x6e, 0x1a, 0x1b, 0x2e, 0x63, 0x6f,
	0x72, 0x65, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x6d, 0x65, 0x6e,
	0x74, 0x53, 0x74, 0x65, 0x70, 0x4f, 0x75, 0x74, 0x12, 0x46, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x72, 0x6d, 0x4c, 0x69, 0x76, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x17, 0x2e, 0x63,
	0x6f, 0x72, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x4c, 0x69, 0x76, 0x65, 0x43,
	0x6c, 0x61, 0x73, 0x49, 0x6e, 0x1a, 0x19, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x72, 0x6d, 0x4c, 0x69, 0x76, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x4f, 0x75, 0x74,
	0x12, 0x36, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x12, 0x0b, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x17, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x4f, 0x75, 0x74, 0x12, 0x4a, 0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x72, 0x6d, 0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x19, 0x2e,
	0x63, 0x6f, 0x72, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x45, 0x6e, 0x72, 0x6f,
	0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x1a, 0x1a, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x6d, 0x65, 0x6e,
	0x74, 0x4f, 0x75, 0x74, 0x12, 0x44, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x50, 0x65, 0x6e, 0x64, 0x69,
	0x6e, 0x67, 0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x0b, 0x2e,
	0x63, 0x6f, 0x72, 0x65, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1e, 0x2e, 0x63, 0x6f, 0x72,
	0x65, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x45, 0x6e, 0x72, 0x6f,
	0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x4f, 0x75, 0x74, 0x12, 0x2e, 0x0a, 0x0d, 0x47, 0x65,
	0x74, 0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x0b, 0x2e, 0x63, 0x6f,
	0x72, 0x65, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x10, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e,
	0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x3c, 0x0a, 0x0f, 0x45, 0x6e,
	0x72, 0x6f, 0x6c, 0x6c, 0x42, 0x61, 0x73, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x2e,
	0x63, 0x6f, 0x72, 0x65, 0x2e, 0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x42, 0x61, 0x73, 0x69, 0x63,
	0x49, 0x6e, 0x66, 0x6f, 0x49, 0x6e, 0x1a, 0x10, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x45, 0x6e,
	0x72, 0x6f, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x42, 0x0a, 0x12, 0x45, 0x6e, 0x72, 0x6f,
	0x6c, 0x6c, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x73, 0x12, 0x1a,
	0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x43, 0x65, 0x72, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x73, 0x49, 0x6e, 0x1a, 0x10, 0x2e, 0x63, 0x6f, 0x72,
	0x65, 0x2e, 0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x3c, 0x0a, 0x0f,
	0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x44, 0x65, 0x6d, 0x6f, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12,
	0x17, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x44, 0x65, 0x6d,
	0x6f, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x49, 0x6e, 0x1a, 0x10, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e,
	0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x46, 0x0a, 0x14, 0x45, 0x6e,
	0x72, 0x6f, 0x6c, 0x6c, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x12, 0x1c, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c,
	0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x49, 0x6e,
	0x1a, 0x10, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x6d, 0x65,
	0x6e, 0x74, 0x42, 0x0a, 0x5a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_teacher_proto_rawDescOnce sync.Once
	file_proto_teacher_proto_rawDescData = file_proto_teacher_proto_rawDesc
)

func file_proto_teacher_proto_rawDescGZIP() []byte {
	file_proto_teacher_proto_rawDescOnce.Do(func() {
		file_proto_teacher_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_teacher_proto_rawDescData)
	})
	return file_proto_teacher_proto_rawDescData
}

var file_proto_teacher_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_teacher_proto_goTypes = []interface{}{
	(*EnrollWithTeacherResult)(nil),  // 0: core.EnrollWithTeacherResult
	(*RegisterTeacherIn)(nil),        // 1: core.RegisterTeacherIn
	(*RegisterTeacherOut)(nil),       // 2: core.RegisterTeacherOut
	(*SearchTeacherIn)(nil),          // 3: core.SearchTeacherIn
	(*SearchTeacherOut)(nil),         // 4: core.SearchTeacherOut
	(*EditEnrollmentStepIn)(nil),     // 5: core.EditEnrollmentStepIn
	(*EditEnrollmentStepOut)(nil),    // 6: core.EditEnrollmentStepOut
	(*ConfirmEnrollmentIn)(nil),      // 7: core.ConfirmEnrollmentIn
	(*ConfirmEnrollmentOut)(nil),     // 8: core.ConfirmEnrollmentOut
	(*ConfirmLiveClasIn)(nil),        // 9: core.ConfirmLiveClasIn
	(*ConfirmLiveClassOut)(nil),      // 10: core.ConfirmLiveClassOut
	(*GetEnrollmentsOut)(nil),        // 11: core.GetEnrollmentsOut
	(*EnrollBasicInfoIn)(nil),        // 12: core.EnrollBasicInfoIn
	(*Certificate)(nil),              // 13: core.Certificate
	(*EnrollCertificatesIn)(nil),     // 14: core.EnrollCertificatesIn
	(*EnrollDemoClassIn)(nil),        // 15: core.EnrollDemoClassIn
	(*EnrollAcceptContractIn)(nil),   // 16: core.EnrollAcceptContractIn
	(*GetPendingEnrollmentsOut)(nil), // 17: core.GetPendingEnrollmentsOut
	(*Enrollment)(nil),               // 18: core.Enrollment
	(*Empty)(nil),                    // 19: core.Empty
}
var file_proto_teacher_proto_depIdxs = []int32{
	18, // 0: core.GetEnrollmentsOut.enrollments:type_name -> core.Enrollment
	13, // 1: core.EnrollCertificatesIn.certificates:type_name -> core.Certificate
	0,  // 2: core.GetPendingEnrollmentsOut.enrollments:type_name -> core.EnrollWithTeacherResult
	1,  // 3: core.TeacherService.RegisterTeacher:input_type -> core.RegisterTeacherIn
	3,  // 4: core.TeacherService.SearchTeachers:input_type -> core.SearchTeacherIn
	5,  // 5: core.TeacherService.EditEnrollmentStep:input_type -> core.EditEnrollmentStepIn
	9,  // 6: core.TeacherService.ConfirmLiveClass:input_type -> core.ConfirmLiveClasIn
	19, // 7: core.TeacherService.GetEnrollments:input_type -> core.Empty
	7,  // 8: core.TeacherService.ConfirmEnrollment:input_type -> core.ConfirmEnrollmentIn
	19, // 9: core.TeacherService.GetPendingEnrollments:input_type -> core.Empty
	19, // 10: core.TeacherService.GetEnrollment:input_type -> core.Empty
	12, // 11: core.TeacherService.EnrollBasicInfo:input_type -> core.EnrollBasicInfoIn
	14, // 12: core.TeacherService.EnrollCertificates:input_type -> core.EnrollCertificatesIn
	15, // 13: core.TeacherService.EnrollDemoClass:input_type -> core.EnrollDemoClassIn
	16, // 14: core.TeacherService.EnrollAcceptContract:input_type -> core.EnrollAcceptContractIn
	2,  // 15: core.TeacherService.RegisterTeacher:output_type -> core.RegisterTeacherOut
	4,  // 16: core.TeacherService.SearchTeachers:output_type -> core.SearchTeacherOut
	6,  // 17: core.TeacherService.EditEnrollmentStep:output_type -> core.EditEnrollmentStepOut
	10, // 18: core.TeacherService.ConfirmLiveClass:output_type -> core.ConfirmLiveClassOut
	11, // 19: core.TeacherService.GetEnrollments:output_type -> core.GetEnrollmentsOut
	8,  // 20: core.TeacherService.ConfirmEnrollment:output_type -> core.ConfirmEnrollmentOut
	17, // 21: core.TeacherService.GetPendingEnrollments:output_type -> core.GetPendingEnrollmentsOut
	18, // 22: core.TeacherService.GetEnrollment:output_type -> core.Enrollment
	18, // 23: core.TeacherService.EnrollBasicInfo:output_type -> core.Enrollment
	18, // 24: core.TeacherService.EnrollCertificates:output_type -> core.Enrollment
	18, // 25: core.TeacherService.EnrollDemoClass:output_type -> core.Enrollment
	18, // 26: core.TeacherService.EnrollAcceptContract:output_type -> core.Enrollment
	15, // [15:27] is the sub-list for method output_type
	3,  // [3:15] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_teacher_proto_init() }
func file_proto_teacher_proto_init() {
	if File_proto_teacher_proto != nil {
		return
	}
	file_proto_schemas_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_teacher_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnrollWithTeacherResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_teacher_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterTeacherIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_teacher_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterTeacherOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_teacher_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchTeacherIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_teacher_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchTeacherOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_teacher_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditEnrollmentStepIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_teacher_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditEnrollmentStepOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_teacher_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfirmEnrollmentIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_teacher_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfirmEnrollmentOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_teacher_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfirmLiveClasIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_teacher_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfirmLiveClassOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_teacher_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEnrollmentsOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_teacher_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnrollBasicInfoIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_teacher_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Certificate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_teacher_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnrollCertificatesIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_teacher_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnrollDemoClassIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_teacher_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnrollAcceptContractIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_teacher_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPendingEnrollmentsOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_teacher_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_teacher_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_teacher_proto_goTypes,
		DependencyIndexes: file_proto_teacher_proto_depIdxs,
		MessageInfos:      file_proto_teacher_proto_msgTypes,
	}.Build()
	File_proto_teacher_proto = out.File
	file_proto_teacher_proto_rawDesc = nil
	file_proto_teacher_proto_goTypes = nil
	file_proto_teacher_proto_depIdxs = nil
}
