// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: proto/todolist.proto

package pb

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTodosOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Todos []*Todo `protobuf:"bytes,1,rep,name=todos,proto3" json:"todos,omitempty"`
}

func (x *GetTodosOut) Reset() {
	*x = GetTodosOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_todolist_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTodosOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTodosOut) ProtoMessage() {}

func (x *GetTodosOut) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todolist_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTodosOut.ProtoReflect.Descriptor instead.
func (*GetTodosOut) Descriptor() ([]byte, []int) {
	return file_proto_todolist_proto_rawDescGZIP(), []int{0}
}

func (x *GetTodosOut) GetTodos() []*Todo {
	if x != nil {
		return x.Todos
	}
	return nil
}

type NewTodoIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *NewTodoIn) Reset() {
	*x = NewTodoIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_todolist_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewTodoIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewTodoIn) ProtoMessage() {}

func (x *NewTodoIn) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todolist_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewTodoIn.ProtoReflect.Descriptor instead.
func (*NewTodoIn) Descriptor() ([]byte, []int) {
	return file_proto_todolist_proto_rawDescGZIP(), []int{1}
}

func (x *NewTodoIn) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type NewTodoOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Todo *Todo `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
}

func (x *NewTodoOut) Reset() {
	*x = NewTodoOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_todolist_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewTodoOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewTodoOut) ProtoMessage() {}

func (x *NewTodoOut) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todolist_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewTodoOut.ProtoReflect.Descriptor instead.
func (*NewTodoOut) Descriptor() ([]byte, []int) {
	return file_proto_todolist_proto_rawDescGZIP(), []int{2}
}

func (x *NewTodoOut) GetTodo() *Todo {
	if x != nil {
		return x.Todo
	}
	return nil
}

type EditTodoOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Todo *Todo `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
}

func (x *EditTodoOut) Reset() {
	*x = EditTodoOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_todolist_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditTodoOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditTodoOut) ProtoMessage() {}

func (x *EditTodoOut) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todolist_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditTodoOut.ProtoReflect.Descriptor instead.
func (*EditTodoOut) Descriptor() ([]byte, []int) {
	return file_proto_todolist_proto_rawDescGZIP(), []int{3}
}

func (x *EditTodoOut) GetTodo() *Todo {
	if x != nil {
		return x.Todo
	}
	return nil
}

type CheckTodoIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Completed bool   `protobuf:"varint,2,opt,name=completed,proto3" json:"completed,omitempty"`
}

func (x *CheckTodoIn) Reset() {
	*x = CheckTodoIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_todolist_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckTodoIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTodoIn) ProtoMessage() {}

func (x *CheckTodoIn) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todolist_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTodoIn.ProtoReflect.Descriptor instead.
func (*CheckTodoIn) Descriptor() ([]byte, []int) {
	return file_proto_todolist_proto_rawDescGZIP(), []int{4}
}

func (x *CheckTodoIn) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CheckTodoIn) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

type CheckTodoOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Todo *Todo `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
}

func (x *CheckTodoOut) Reset() {
	*x = CheckTodoOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_todolist_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckTodoOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTodoOut) ProtoMessage() {}

func (x *CheckTodoOut) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todolist_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTodoOut.ProtoReflect.Descriptor instead.
func (*CheckTodoOut) Descriptor() ([]byte, []int) {
	return file_proto_todolist_proto_rawDescGZIP(), []int{5}
}

func (x *CheckTodoOut) GetTodo() *Todo {
	if x != nil {
		return x.Todo
	}
	return nil
}

type DeleteTodoIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteTodoIn) Reset() {
	*x = DeleteTodoIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_todolist_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTodoIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTodoIn) ProtoMessage() {}

func (x *DeleteTodoIn) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todolist_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTodoIn.ProtoReflect.Descriptor instead.
func (*DeleteTodoIn) Descriptor() ([]byte, []int) {
	return file_proto_todolist_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteTodoIn) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_proto_todolist_proto protoreflect.FileDescriptor

var file_proto_todolist_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x6f, 0x64, 0x6f, 0x6c, 0x69, 0x73, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63, 0x6f, 0x72, 0x65, 0x1a, 0x1b, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d,
	0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x74, 0x6f, 0x64, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2f, 0x0a, 0x0b, 0x47,
	0x65, 0x74, 0x54, 0x6f, 0x64, 0x6f, 0x73, 0x4f, 0x75, 0x74, 0x12, 0x20, 0x0a, 0x05, 0x74, 0x6f,
	0x64, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x63, 0x6f, 0x72, 0x65,
	0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x52, 0x05, 0x74, 0x6f, 0x64, 0x6f, 0x73, 0x22, 0x25, 0x0a, 0x09,
	0x4e, 0x65, 0x77, 0x54, 0x6f, 0x64, 0x6f, 0x49, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x22, 0x2c, 0x0a, 0x0a, 0x4e, 0x65, 0x77, 0x54, 0x6f, 0x64, 0x6f, 0x4f, 0x75,
	0x74, 0x12, 0x1e, 0x0a, 0x04, 0x74, 0x6f, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x52, 0x04, 0x74, 0x6f, 0x64,
	0x6f, 0x22, 0x2d, 0x0a, 0x0b, 0x45, 0x64, 0x69, 0x74, 0x54, 0x6f, 0x64, 0x6f, 0x4f, 0x75, 0x74,
	0x12, 0x1e, 0x0a, 0x04, 0x74, 0x6f, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a,
	0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x52, 0x04, 0x74, 0x6f, 0x64, 0x6f,
	0x22, 0x3b, 0x0a, 0x0b, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x6f, 0x64, 0x6f, 0x49, 0x6e, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x22, 0x2e, 0x0a,
	0x0c, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x6f, 0x64, 0x6f, 0x4f, 0x75, 0x74, 0x12, 0x1e, 0x0a,
	0x04, 0x74, 0x6f, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x63, 0x6f,
	0x72, 0x65, 0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x52, 0x04, 0x74, 0x6f, 0x64, 0x6f, 0x22, 0x1e, 0x0a,
	0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x6f, 0x64, 0x6f, 0x49, 0x6e, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x32, 0x90, 0x03,
	0x0a, 0x0f, 0x54, 0x6f, 0x64, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x35, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x64, 0x6f, 0x73, 0x12, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x11, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x47, 0x65, 0x74,
	0x54, 0x6f, 0x64, 0x6f, 0x73, 0x4f, 0x75, 0x74, 0x12, 0x2c, 0x0a, 0x07, 0x4e, 0x65, 0x77, 0x54,
	0x6f, 0x64, 0x6f, 0x12, 0x0f, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x4e, 0x65, 0x77, 0x54, 0x6f,
	0x64, 0x6f, 0x49, 0x6e, 0x1a, 0x10, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x4e, 0x65, 0x77, 0x54,
	0x6f, 0x64, 0x6f, 0x4f, 0x75, 0x74, 0x12, 0x29, 0x0a, 0x08, 0x45, 0x64, 0x69, 0x74, 0x54, 0x6f,
	0x64, 0x6f, 0x12, 0x0a, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x1a, 0x11,
	0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x54, 0x6f, 0x64, 0x6f, 0x4f, 0x75,
	0x74, 0x12, 0x32, 0x0a, 0x09, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x6f, 0x64, 0x6f, 0x12, 0x11,
	0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x6f, 0x64, 0x6f, 0x49,
	0x6e, 0x1a, 0x12, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x6f,
	0x64, 0x6f, 0x4f, 0x75, 0x74, 0x12, 0x38, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54,
	0x6f, 0x64, 0x6f, 0x12, 0x12, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x54, 0x6f, 0x64, 0x6f, 0x49, 0x6e, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12,
	0x3d, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x6c, 0x6c, 0x12, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x40,
	0x0a, 0x0e, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64,
	0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x42, 0x0a, 0x5a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_todolist_proto_rawDescOnce sync.Once
	file_proto_todolist_proto_rawDescData = file_proto_todolist_proto_rawDesc
)

func file_proto_todolist_proto_rawDescGZIP() []byte {
	file_proto_todolist_proto_rawDescOnce.Do(func() {
		file_proto_todolist_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_todolist_proto_rawDescData)
	})
	return file_proto_todolist_proto_rawDescData
}

var file_proto_todolist_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_todolist_proto_goTypes = []interface{}{
	(*GetTodosOut)(nil),  // 0: core.GetTodosOut
	(*NewTodoIn)(nil),    // 1: core.NewTodoIn
	(*NewTodoOut)(nil),   // 2: core.NewTodoOut
	(*EditTodoOut)(nil),  // 3: core.EditTodoOut
	(*CheckTodoIn)(nil),  // 4: core.CheckTodoIn
	(*CheckTodoOut)(nil), // 5: core.CheckTodoOut
	(*DeleteTodoIn)(nil), // 6: core.DeleteTodoIn
	(*Todo)(nil),         // 7: core.Todo
	(*empty.Empty)(nil),  // 8: google.protobuf.Empty
}
var file_proto_todolist_proto_depIdxs = []int32{
	7,  // 0: core.GetTodosOut.todos:type_name -> core.Todo
	7,  // 1: core.NewTodoOut.todo:type_name -> core.Todo
	7,  // 2: core.EditTodoOut.todo:type_name -> core.Todo
	7,  // 3: core.CheckTodoOut.todo:type_name -> core.Todo
	8,  // 4: core.TodoListService.GetTodos:input_type -> google.protobuf.Empty
	1,  // 5: core.TodoListService.NewTodo:input_type -> core.NewTodoIn
	7,  // 6: core.TodoListService.EditTodo:input_type -> core.Todo
	4,  // 7: core.TodoListService.CheckTodo:input_type -> core.CheckTodoIn
	6,  // 8: core.TodoListService.DeleteTodo:input_type -> core.DeleteTodoIn
	8,  // 9: core.TodoListService.CompleteAll:input_type -> google.protobuf.Empty
	8,  // 10: core.TodoListService.ClearCompleted:input_type -> google.protobuf.Empty
	0,  // 11: core.TodoListService.GetTodos:output_type -> core.GetTodosOut
	2,  // 12: core.TodoListService.NewTodo:output_type -> core.NewTodoOut
	3,  // 13: core.TodoListService.EditTodo:output_type -> core.EditTodoOut
	5,  // 14: core.TodoListService.CheckTodo:output_type -> core.CheckTodoOut
	8,  // 15: core.TodoListService.DeleteTodo:output_type -> google.protobuf.Empty
	8,  // 16: core.TodoListService.CompleteAll:output_type -> google.protobuf.Empty
	8,  // 17: core.TodoListService.ClearCompleted:output_type -> google.protobuf.Empty
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_todolist_proto_init() }
func file_proto_todolist_proto_init() {
	if File_proto_todolist_proto != nil {
		return
	}
	file_proto_todo_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_todolist_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTodosOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_todolist_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewTodoIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_todolist_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewTodoOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_todolist_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditTodoOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_todolist_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckTodoIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_todolist_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckTodoOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_todolist_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTodoIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_todolist_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_todolist_proto_goTypes,
		DependencyIndexes: file_proto_todolist_proto_depIdxs,
		MessageInfos:      file_proto_todolist_proto_msgTypes,
	}.Build()
	File_proto_todolist_proto = out.File
	file_proto_todolist_proto_rawDesc = nil
	file_proto_todolist_proto_goTypes = nil
	file_proto_todolist_proto_depIdxs = nil
}
